[project]
name = "nlp-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=4.4.2",
    "peft>=0.18.0",
    "torch>=2.9.1",
    "transformers>=4.57.3",
]
